//{{NO_DEPENDENCIES}}
// Archivo de inclusión generado de Microsoft Visual C++.
// Usado por Project30.rc
//
#define IDD_DIALOG1                     101
#define IDD_DIALOG2                     102
#define IDD_DIALOG3                     103
#define IDD_DIALOG4                     104
#define IDR_MENU1                       109
#define IDD_DIALOG5                     110
#define IDD_DIALOG6                     112
#define IDD_DIALOG7                     114
#define IDD_DIALOG8                     116
#define IDD_DIALOG9                     118
#define IDD_DIALOG10                    119
#define IDD_DIALOG11                    122
#define IDD_DIALOG12                    124
#define IDD_DIALOG13                    126
#define IDD_DIALOG14                    128
#define IDD_DIALOG15                    130
#define IDD_DIALOG16                    132
#define IDD_DIALOG17                    134
#define IDD_DIALOG18                    136
#define IDC_BUTTON1                     1001
#define IDC_BUTTON2                     1002
#define IDC_BUTTON3                     1003
#define IDC_EDIT1                       1004
#define IDC_EDIT2                       1005
#define cantclientes                    1005
#define IDC_EDIT3                       1006
#define cantconsu                       1006
#define cantpromoi                      1007
#define IDC_RADIO1                      1007
#define nomcomlis                       1007
#define desccons                        1007
#define cantpromoa                      1008
#define IDC_RADIO2                      1008
#define alilis                          1008
#define totalcons                       1008
#define ComercioU                       1009
#define cantconcli                      1009
#define ContraU                         1010
#define Nombre_U                        1011
#define Can                             1012
#define regisU                          1013
#define actU_n                          1014
#define EMAILCL                         1014
#define actU_A                          1015
#define COMCL                           1015
#define CargaI                          1016
#define ContraU2                        1016
#define FECHACL                         1016
#define Picture1                        1017
#define IDC_LIST1                       1018
#define IDC_RADIO3                      1019
#define IDC_RADIO4                      1020
#define comlis                          1021
#define nomulis                         1022
#define conlis                          1023
#define ELIMINAR                        1024
#define IDC_RADIO5                      1025
#define IDC_RADIO6                      1026
#define IDC_LIST2                       1027
#define NUEVACONTRAU                    1028
#define guardarcontra                   1029
#define regresarcontra                  1030
#define NOMBRECL                        1031
#define ALIASCL                         1032
#define TELCL                           1033
#define GUARDARCL                       1034
#define REGRESARCL                      1035
#define ACTUALIZAR                      1036
#define nomcllis                        1036
#define REGRESAR                        1037
#define alicllis                        1037
#define estatic                         1038
#define emailcllis                      1039
#define comcllis                        1040
#define telecllis                       1041
#define IDC_LIST3                       1042
#define ACTCLLIS                        1043
#define ELICLLIS                        1044
#define REGCLLIS                        1045
#define BCOM                            1046
#define BORNOM                          1047
#define BORCON                          1048
#define BORNOMC                         1049
#define BOALI                           1050
#define BORU                            1051
#define BACKB                           1052
#define BNOMCL                          1053
#define BALICL                          1054
#define BTELCL                          1055
#define ITECELB                         1056
#define BCOMCLI                         1057
#define IELICL                          1058
#define IREGCL                          1059
#define guardaractcl                    1060
#define regresaractcl                   1061
#define IDC_LIST4                       1062
#define nomactcl                        1063
#define aliactcl                        1064
#define telactcl                        1065
#define emailactcl                      1066
#define comactcl                        1067
#define promonom                        1068
#define promomon                        1069
#define promodesc                       1070
#define IDC_RADIO7A                     1071
#define IDC_RADIO8I                     1072
#define FECHAPROMO                      1073
#define GUARDARPROMO                    1074
#define REGRESARPROMO                   1075
#define IDC_LIST5                       1076
#define promonomlis                     1077
#define promonlis                       1078
#define promodesclis                    1079
#define estatuslis                      1080
#define promoactlis                     1081
#define promoelim                       1082
#define promoreglis                     1083
#define lecnom                          1084
#define lecmon                          1085
#define lecdesc                         1086
#define lecfecha                        1087
#define IDC_RADIO9A                     1088
#define IDC_RADIO10I                    1089
#define actguarprom                     1090
#define actcanprom                      1091
#define IDC_LIST6                       1092
#define BPN                             1093
#define BPM                             1094
#define BPD                             1095
#define BPE                             1096
#define BPELIMINAR                      1097
#define BPREGRESAR                      1098
#define NOMPROD                         1099
#define PRECIOPRO                       1100
#define GUARDARPROD                     1101
#define CANCELARPROD                    1102
#define IDC_COMBO1                      1103
#define montocons                       1104
#define fechacons                       1105
#define subtotalcons                    1106
#define guardarcons                     1107
#define regresarconsu                   1108
#define IDC_COMBO2                      1109
#define IDC_LIST7                       1109
#define cienteliscons                   1110
#define prodliscons                     1111
#define unidadesconslis                 1112
#define subtotalconslis                 1113
#define descconslis                     1114
#define totalconslis                    1115
#define IDBACKLIS                       1116
#define foto                            1125
#define NOM1                            1126
#define FOTON1                          1127
#define FOTON2                          1128
#define NOM2                            1129
#define FOTON3                          1130
#define NOM3                            1131
#define NOM4                            1133
#define FOTON4                          1134
#define FOTON5                          1135
#define NOM5                            1136
#define FOTON6                          1137
#define NOM6                            1138
#define FOTON7                          1139
#define NOM7                            1140
#define FOTON8                          1141
#define NOM8                            1142
#define FOTON9                          1143
#define NOM9                            1144
#define FOTON10                         1145
#define NOM10                           1146
#define FOTON11                         1147
#define NOM11                           1148
#define FOTON12                         1149
#define NOM12                           1150
#define FOTON13                         1151
#define NOM13                           1152
#define FOTON14                         1153
#define NOM14                           1154
#define FOTON15                         1155
#define NOM15                           1156
#define ACTLISTA1                       1157
#define ACTLISTA2                       1158
#define ACTLISTA3                       1159
#define ACTLISTA4                       1160
#define ACTLISTA5                       1161
#define ACTLISTA6                       1162
#define ACTLISTA7                       1163
#define actualizarinfo                  1164
#define IDC_DATETIMEPICKER1             1164
#define ID_USUARIOS_ALTADEUSUARIO       40001
#define ID_USUARIOS_ACTUALIZARUSUARIO   40002
#define ID_USUARIOS_BAJADEUSUARIO       40003
#define ID_USUARIOS_RESTABLECERCONTRASE40004 40004
#define ID_USUARIOS_LISTADODEUSUARIOS   40005
#define ID_CLIENTES_ALTADECLIENTES      40006
#define ID_CLIENTES_ACTUALIZARCLIENTE   40007
#define ID_CLIENTES_BAJADECLIENTE       40008
#define ID_CLIENTES_LISTADODECLIENTES   40009
#define ID_PROMOCIONES_ALTADEPROMOCION  40010
#define ID_PROMOCIONES_BAJADEPROMOCION  40011
#define ID_PROMOCIONES_LISTADODEPROMOCIONES 40012
#define ID_CONSUMO_ALTADEPRODUCTOS      40013
#define ID_CONSUMO_ALTADECONSUMO        40014
#define ID_CONSUMO_LISTADODECONSUMOS    40015
#define ID_SALIR_SALIR                  40016
#define ID_CONSUMO_ALTADECONSUMOS       40017
#define ID_PROMOCIONES_ACTUALIZARESTATUS 40018

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         40019
#define _APS_NEXT_CONTROL_VALUE         1165
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
